spring.application.name=CampusHire
spring.datasource.url=jdbc:postgresql://ep-falling-heart-aitlzjw4-pooler.c-4.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_qLum9ZJAotd7&sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qLum9ZJAotd7
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gagantirumareddy@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true